modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issues}"
[[mods]]
modId="${archives_base_name}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${archives_base_name}]]
modId="neoforge"
mandatory=true
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${archives_base_name}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${archives_base_name}]]
modId="create"
mandatory=true
versionRange="${create_neoforge_range}"
ordering="NONE"
side="BOTH"
